# Generated by Django 4.0.4 on 2022-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_description'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='swipedGames',
        ),
        migrations.AddField(
            model_name='customuser',
            name='swipedGames',
            field=models.ManyToManyField(default=None, related_name='SwipedBy', to='games.game'),
        ),
    ]
