# Generated by Django 4.0.4 on 2022-04-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_official_site'),
        ('jwt_auth', '0003_alter_customuser_swipedgames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='swipedGames',
            field=models.ManyToManyField(blank=True, default=None, related_name='SwipedBy', to='games.game'),
        ),
    ]
