# Generated by Django 4.0.4 on 2022-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='official_site',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
