# Generated by Django 4.0.4 on 2022-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_official_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='official_site',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
